name: Plugin Package
description: I have packaged
labels: packaging
title: "[PACKAGE NEW] "
body:
  - type: input
    id: issue
    attributes:
      label: Issue
      description: The Issue this fixes (just use \# notation)
    validations:
      required: true
  - type: checkboxes
    id: pre conditions
    attributes:
      label: Neccesarry Preconditions
      options:
        - label: I added all keybinds as options with a sensible default
          required: true
        - label: I added relevant options (e.g for optional runtimeDeps, runtimeDeps package)
          required: true
        - label: I added a require call (if applicable)
          required: true
        - label: I added all options given to the require call to the options
          required: true
        - label: I added relevant runtimeDeps
          required: true
        - label: I checked this works with the latst yazi version (use your repo as flake input)
          required: true
        - label: I added the relevant test(s) for this plugin (TBD)
          required: true
  - type: checkboxes
    id: chore
    attributes:
      label: chores
      descripiton: "Some Chores: Most of them should not be applicable"
      options:
        - label: I formatted the code using nix fmt
          required: true
        - label: I updated all the modules (if applicable, see issue)
          required: true
        - label: I updated the documentation (if applicable)
          required: true
        - label: I rebuilt all plugins
          required: true
        - label: I tested the change locally
          required: true
        - label: I ran the tests (TBD)
          required: true
